# Generated by Django 5.0.4 on 2025-08-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(help_text='Icon class name', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme for category', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of videos in this category')),
            ],
            options={
                'verbose_name_plural': 'Video Categories',
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('video_url', models.URLField(help_text='YouTube URL or other video embed URL')),
                ('duration', models.DurationField(help_text='Duration of the video')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('presenter', models.CharField(help_text='Name of doctor or presenter', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tv.videocategory')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='tv.videosource')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watch_progress', models.PositiveIntegerField(default=0, help_text='Progress in seconds')),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
