# Generated by Django 5.2.10 on 2026-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medical condition', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated)', max_length=220, unique=True)),
                ('overview', models.TextField(help_text='Brief overview or description of the condition')),
                ('symptoms', models.TextField(help_text='Signs and symptoms of the condition')),
                ('causes', models.TextField(help_text='Causes and risk factors')),
                ('treatments', models.TextField(help_text='Treatment options and management strategies')),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('endocrinology', 'Endocrinology'), ('oncology', 'Oncology'), ('psychiatry', 'Psychiatry'), ('pediatrics', 'Pediatrics'), ('obstetrics_gynecology', 'Obstetrics & Gynecology'), ('internal_medicine', 'Internal Medicine'), ('emergency_medicine', 'Emergency Medicine'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('pathology', 'Pathology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('otolaryngology', 'Otolaryngology (ENT)'), ('rheumatology', 'Rheumatology'), ('infectious_disease', 'Infectious Disease'), ('nephrology', 'Nephrology'), ('hematology', 'Hematology'), ('general_surgery', 'General Surgery')], help_text='Medical department/specialty that typically handles this condition', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Representative image for this condition', null=True, upload_to='conditions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='health_tech_name_dcaeba_idx'), models.Index(fields=['department'], name='health_tech_departm_f427f0_idx'), models.Index(fields=['created_at'], name='health_tech_created_b1d6d1_idx')],
            },
        ),
    ]
