# Generated by Django 5.0.4 on 2025-08-07 10:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=255, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'This phone number is already in use.'}, max_length=128, null=True, region=None, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('INDIVIDUAL_PROVIDER', 'Individual Provider'), ('ORGANIZATION', 'Healthcare Organization'), ('PATIENT', 'Patient'), ('ADMIN', 'Administrator')], default='PATIENT', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('PHYSICIAN', 'Physician'), ('NURSE_PRACTITIONER', 'Nurse Practitioner'), ('PHYSICIAN_ASSISTANT', 'Physician Assistant'), ('THERAPIST', 'Therapist'), ('PHARMACIST', 'Pharmacist'), ('DENTIST', 'Dentist'), ('PSYCHOLOGIST', 'Psychologist'), ('OTHER', 'Other Healthcare Professional')], default='PHYSICIAN', max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('npi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='provider_pictures/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('brand_color', models.CharField(blank=True, help_text='Hex color code', max_length=20, null=True)),
                ('insurance_accepted', models.TextField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_types', models.JSONField(default=list, help_text='List of appointment types offered (IN_PERSON, VIDEO, PHONE)')),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('video_consultation_link', models.URLField(blank=True, help_text='Default video consultation platform link', null=True)),
                ('advance_booking_days', models.IntegerField(default=90, help_text='How many days in advance patients can book')),
                ('minimum_notice_hours', models.IntegerField(default=24, help_text='Minimum hours notice required for booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('URGENT_CARE', 'Urgent Care'), ('IMAGING_CENTER', 'Imaging Center'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('MENTAL_HEALTH_CENTER', 'Mental Health Center'), ('REHABILITATION_CENTER', 'Rehabilitation Center'), ('NURSING_HOME', 'Nursing Home'), ('MEDICAL_GROUP', 'Medical Group'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('brand_color', models.CharField(blank=True, help_text='Hex color code', max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('business_license', models.CharField(blank=True, max_length=100, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('insurance_accepted', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(choices=[('MAIN', 'Main Location'), ('BRANCH', 'Branch'), ('SATELLITE', 'Satellite Office'), ('SPECIALIZED', 'Specialized Unit'), ('PRIVATE_PRACTICE', 'Private Practice')], default='MAIN', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hours_of_operation', models.TextField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('individual_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.individualproviderprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.organizationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor'), ('VOLUNTEER', 'Volunteer'), ('CONSULTING', 'Consulting'), ('PRIVILEGES', 'Hospital Privileges')], default='EMPLOYEE', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('individual_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_affiliations', to='accounts.individualproviderprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_provider_affiliations', to='accounts.organizationprofile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_affiliations', to='accounts.providerlocation')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='providerlocation',
            constraint=models.CheckConstraint(check=models.Q(('individual_provider__isnull', False), ('organization__isnull', False), _connector='OR'), name='location_must_have_provider'),
        ),
        migrations.AddConstraint(
            model_name='providerlocation',
            constraint=models.CheckConstraint(check=models.Q(('individual_provider__isnull', False), ('organization__isnull', False), _negated=True), name='location_cannot_have_both_providers'),
        ),
        migrations.AlterUniqueTogether(
            name='provideraffiliation',
            unique_together={('individual_provider', 'organization', 'location')},
        ),
    ]
