# Generated by Django 5.0.4 on 2025-08-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshops', '0004_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
