# Generated by Django 5.0.4 on 2025-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshops', '0005_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
